AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  코인 30 회복

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  FrogFullCoinBatchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      ReservedConcurrentExecutions: 2  
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src
      Handler: bootstrap
      PackageType: Zip
      MemorySize: 128
      Runtime: provided.al2023
      VpcConfig:
        SecurityGroupIds:
          - sg-07fc0de84a8e119c0 #idea_dev_private_int
        SubnetIds:
          - subnet-017c0de3d874cab7e #idea-private-b1
          - subnet-00bd54fe53b26180d #idea-private-c1
      Architectures:
        - x86_64
      Events:
        CWSchedule:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 0 * * ? *)'
      ReservedConcurrentExecutions: 1
      Policies:
        - Statement:
            - Sid: SSMDescribeParametersPolicy
              Effect: Allow
              Action:
                - ssm:DescribeParameters
              Resource: '*'
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource: '*'
      Environment:
        Variables:
          PROJECT: 'frog'
          ENV: 'dev'
          REGION: 'ap-northeast-2'

Outputs:
  FrogFullCoinBatchFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt FrogFullCoinBatchFunction.Arn
