version = 0.1

[apne2-dev.deploy]
[apne2-dev.deploy.parameters]
stack_name = "food-name-recommendation-apne2-dev"
s3_bucket = "food-name-recommendation"
s3_prefix = "food-name-recommendation-apne2-dev"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
[default.deploy.parameters]
stack_name = "food-name-recommendation-app"
resolve_s3 = true
s3_prefix = "food-name-recommendation-app"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
