# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[apne2-dev.deploy]
[apne2-dev.deploy.parameters]
stack_name = "food-apne2-dev"
s3_bucket = "food-info-empty-batch"
s3_prefix = "food-info-empty-batch"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []